export const MOTIVATIONAL_QUOTES = [
  "The secret of getting ahead is getting started.",
  "Action is the foundational key to all success.",
  "Don't watch the clock; do what it does. Keep going.",
  "You don't have to be great to start, but you have to start to be great.",
  "Small steps every day lead to giant leaps over time.",
  "Your future is created by what you do today, not tomorrow.",
  "Discipline is the bridge between goals and accomplishment.",
  "The only bad workout is the one that didn't happen.",
  "Focus on progress, not perfection.",
  "Every morning you have two choices: continue to sleep with your dreams or wake up and chase them.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "You are capable of amazing things.",
  "Your limitation—it's only your imagination.",
  "Sometimes later becomes never. Do it now.",
  "Great minds have purposes, others have wishes.",
  "Winners are not people who never fail, but people who never quit.",
  "Start where you are. Use what you have. Do what you can.",
  "Keep going. Everything you need will come to you.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Be the change you wish to see in the world.",
  "Life is short. Do stuff that matters.",
  "Strive for progress, not perfection.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "An obstacle is often a stepping stone.",
  "Believe you can and you're halfway there.",
  "It always seems impossible until it's done.",
  "You get what you work for, not what you wish for.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don't limit your challenges. Challenge your limits.",
  "Everything you've ever wanted is on the other side of fear.",
  "Be stronger than your excuses.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The only way to do great work is to love what you do.",
  "Innovation distinguishes between a leader and a follower.",
  "Stay hungry, stay foolish.",
  "Your time is limited, so don't waste it living someone else's life.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It is during our darkest moments that we must focus to see the light.",
  "Try to be a rainbow in someone's cloud.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "In the end, it's not the years in your life that count, it's the life in your years.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "If life were predictable it would cease to be life, and be without flavor.",
  "If you look at what you have in life, you'll always have more.",
  "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
  "Life is not measured by the number of breaths we take.",
  "The only impossible journey is the one you never begin.",
  "In this life we cannot always do great things. But we can do small things with great love.",
  "Only a life lived for others is a life worthwhile.",
  "The purpose of our lives is to be happy.",
  "You only live once, but if you do it right, once is enough.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself in any direction you choose.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Never let the fear of striking out keep you from playing the game.",
  "Money and success don't change people; they merely amplify what is already there.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Not how long, but how well you have lived is the main thing.",
  "If life were predictable it would cease to be life.",
  "In the end, it's not the years in your life that count.",
  "Spread love everywhere you go.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't go around saying the world owes you a living.",
  "You must be the change you wish to see in the world.",
  "Spread love everywhere you go.",
  "I have learned over the years that when one's mind is made up, this diminishes fear.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "It's kind of fun to do the impossible.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "The secret of getting ahead is getting started.",
  "All you need is the plan, the road map, and the courage to press on to your destination.",
  "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.",
  "Life is what we make it, always has been, always will be.",
  "The most common way people give up their power is by thinking they don't have any.",
  "The mind is everything. What you think you become.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "An unexamined life is not worth living.",
  "Spread love everywhere you go.",
  "You are enough. You have enough. You do enough.",
  "Make today so awesome, yesterday gets jealous.",
  "Earn it. Every. Single. Day.",
] as const;

export const getDailyQuote = (): string => {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return MOTIVATIONAL_QUOTES[dayOfYear % MOTIVATIONAL_QUOTES.length];
};
